@startmindmap

title Mind Map - Sharpen your "Architecture Documentation" Saw

* Session
** Architectural Decision\nRecords (ADRs)  
*** history
*** examples
*** future
** humor
*** overused meme
*** fake quotes
*** GenAI references
** Diagrams-as-Code
*** PlantUML
*** AWS Icons for PlantUML
*** Mermaid
*** C4
*** Structurizr
** Call to Action

@endmindmap
